/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiDiscoverFeedRouteImport } from './routes/api/discover-feed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiscoverFeedRoute = ApiDiscoverFeedRouteImport.update({
  id: '/api/discover-feed',
  path: '/api/discover-feed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/discover-feed': typeof ApiDiscoverFeedRoute
  '/api/feed': typeof ApiFeedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/discover-feed': typeof ApiDiscoverFeedRoute
  '/api/feed': typeof ApiFeedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/discover-feed': typeof ApiDiscoverFeedRoute
  '/api/feed': typeof ApiFeedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/discover-feed' | '/api/feed'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/discover-feed' | '/api/feed'
  id: '__root__' | '/' | '/api/discover-feed' | '/api/feed'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDiscoverFeedRoute: typeof ApiDiscoverFeedRoute
  ApiFeedRoute: typeof ApiFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/discover-feed': {
      id: '/api/discover-feed'
      path: '/api/discover-feed'
      fullPath: '/api/discover-feed'
      preLoaderRoute: typeof ApiDiscoverFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDiscoverFeedRoute: ApiDiscoverFeedRoute,
  ApiFeedRoute: ApiFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
